export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_IS_FETCHING = 'SET_IS_FETHCING';
export const PRODUCTS_IS_RECEIVED = 'PRODUCTS_RECEIVED';
export const PRODUCT_IS_RECEIVED = 'PRODUCT_RECEIVED';
export const PRODUCT_IS_REMOVED = 'PRODUCT_REMOVED';
export const SET_IS_SUBMITTING = "SET_IS_SUBMITTIN";